apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gatus.yml
  - gatus-route.yml
  - gatus-secrets.yml

configMapGenerator:
  - name: gatus-config
    namespace: gatus
    files:
      - config.yml
    options:
      disableNameSuffixHash: true
