---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  install:
    createNamespace: true
  interval: 1m0s
  storageNamespace: flux-system
  targetNamespace: external-secrets
