---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openbao
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://openbao.github.io/openbao-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
  namespace: flux-system
spec:
  chart:
    spec:
      chart: openbao
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openbao
  interval: 1m0s
  values:
    server:
      dataStorage:
        storageClass: nfs-client
      ha:
        enabled: true
        raft:
          enabled: true
  targetNamespace: openbao
  install:
    createNamespace: true
