apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault.cobbler.gordns.net
  namespace: sandbox
spec:
  # Secret names are always required.
  secretName: vault-tls-cert
  commonName: vault.cobbler.gordns.net

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  # At least one of commonName (possibly through literalSubject), dnsNames, uris, emailAddresses, ipAddresses or otherNames is required.
  dnsNames:
    - vault.cobbler.gordns.net

  # Issuer references are always required.
  issuerRef:
    name: vault-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
