apiVersion: v1
kind: Namespace
metadata:
  name: internal-gateway
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: star.cobbler.gordns.net
  namespace: internal-gateway
spec:
  # Secret names are always required.
  secretName: cobbler-wildcard
  commonName: '*.cobbler.gordns.net'

  # At least one of commonName (possibly through literalSubject), dnsNames, uris, emailAddresses, ipAddresses or otherNames is required.
  dnsNames:
    - '*.cobbler.gordns.net'

  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: internal-gateway
spec:
  gatewayClassName: cilium
  infrastructure:
    labels:
      expose: "true"
  listeners:
  - name: https
    port: 443
    protocol: HTTPS
    hostname: "*.cobbler.gordns.net"
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
        - name: cobbler-wildcard
  - name: http
    port: 80
    protocol: HTTP
    hostname: "*.cobbler.gordns.net"
#    allowedRoutes:
#      namespaces:
#        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: redirect-to-https
  namespace: internal-gateway
spec:
  parentRefs:
  - name: internal
    namespace: internal-gateway
    sectionName: http
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 302
