---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cilium
      version: "1.19.5"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
  interval: 1m0s
  releaseName: cilium
  targetNamespace: kube-system
  upgrade:
    crds: CreateReplace
  values:
    cluster:
      name: kubernetes
    cni:
      binPath: /var/lib/cni/bin
    enable-host-legacy-routing: true
    externalIPs:
      enabled: true
    k8s:
      apiServerURLs:
      - https://10.3.14.6:6443
      - https://10.3.14.7:6443
      - https://10.3.14.8:6443
    k8sServiceHost: 10.3.14.5
    k8sServicePort: 6443
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
    operator:
      replicas: 1
    routingMode: tunnel
    tunnelProtocol: vxlan
