---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: Cilium
  interval: 1m0s
  values:
    cluster:
      name: k3s-prod
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: 10.42.0.0/16
    k8sServiceHost: k3s-prod.gordns.net
    k8sServicePort: 6443
    kubeProxyReplacement: "true"
    operator:
      replicas: 1
    rollOutCiliumPods: true
    routingMode: tunnel
